version: "3.8"
services:
# =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
# All The Mods 8
  allthemods8:
    image: wotupfoo/allthemods8:latest

# If you are running the server with the user `root` you need to uncomment this line
#    user: root

# If you want to be able to exec in with the right characters woring, uncomment these lines
#    tty: true
#    stdin_open: true

#   Map the network ports from the container to the host so that it can be accessed
    ports:
        # Minecraft Server Port
        - "25565:25565"
        # Remote admin control (RCON) Port
#        - "25575:25575"

# The persistent storage directory to save the install. You MUST have this, otherwise your entire server
# will be lost if you stop the container.
    volumes:
      - ./allthemods8:/data

# Environment variable overrides from the defaults.

    environment:
# You must have this set to true to accept the End User License Agreement terms and conditions
        - EULA=true
